"""
Minecraft 物品 中文名 → 英文名 (snake_case ID) 映射表

用于 query_item MCP tool 的第一层精确/子串匹配。
未覆盖的物品由第二层嵌入模型兜底。
"""

# 按类别组织，方便后续增补
CN_TO_EN: dict[str, str] = {
    # ── 矿物 / 资源 ──
    "石头": "stone",
    "圆石": "cobblestone",
    "安山岩": "andesite",
    "闪长岩": "diorite",
    "花岗岩": "granite",
    "深板岩": "deepslate",
    "圆石深板岩": "cobbled_deepslate",
    "砂岩": "sandstone",
    "红砂岩": "red_sandstone",
    "下界岩": "netherrack",
    "末地石": "end_stone",
    "黑曜石": "obsidian",
    "基岩": "bedrock",
    "泥土": "dirt",
    "草方块": "grass_block",
    "沙砾": "gravel",
    "沙子": "sand",
    "红沙": "red_sand",
    "粘土": "clay",
    "煤矿": "coal_ore",
    "铁矿石": "iron_ore",
    "铜矿石": "copper_ore",
    "金矿石": "gold_ore",
    "红石矿石": "redstone_ore",
    "青金石矿石": "lapis_ore",
    "钻石矿石": "diamond_ore",
    "绿宝石矿石": "emerald_ore",
    "下界石英矿石": "nether_quartz_ore",
    "下界金矿石": "nether_gold_ore",
    "深层煤矿": "deepslate_coal_ore",
    "深层铁矿石": "deepslate_iron_ore",
    "深层铜矿石": "deepslate_copper_ore",
    "深层金矿石": "deepslate_gold_ore",
    "深层红石矿石": "deepslate_redstone_ore",
    "深层青金石矿石": "deepslate_lapis_ore",
    "深层钻石矿石": "deepslate_diamond_ore",
    "深层绿宝石矿石": "deepslate_emerald_ore",
    "粗铁": "raw_iron",
    "粗金": "raw_gold",
    "粗铜": "raw_copper",
    "粗铁块": "raw_iron_block",
    "粗金块": "raw_gold_block",
    "粗铜块": "raw_copper_block",
    "铁锭": "iron_ingot",
    "金锭": "gold_ingot",
    "铜锭": "copper_ingot",
    "下界合金锭": "netherite_ingot",
    "下界合金碎片": "netherite_scrap",
    "钻石": "diamond",
    "绿宝石": "emerald",
    "红石粉": "redstone",
    "青金石": "lapis_lazuli",
    "石英": "quartz",
    "煤炭": "coal",
    "木炭": "charcoal",
    "燧石": "flint",

    # ── 木材 / 树 ──
    "橡木原木": "oak_log",
    "云杉原木": "spruce_log",
    "白桦原木": "birch_log",
    "丛林原木": "jungle_log",
    "金合欢原木": "acacia_log",
    "深色橡木原木": "dark_oak_log",
    "红树木原木": "mangrove_log",
    "樱桃原木": "cherry_log",
    "橡木木板": "oak_planks",
    "云杉木板": "spruce_planks",
    "白桦木板": "birch_planks",
    "丛林木板": "jungle_planks",
    "金合欢木板": "acacia_planks",
    "深色橡木木板": "dark_oak_planks",
    "红树木板": "mangrove_planks",
    "樱花木板": "cherry_planks",
    "橡木": "oak_wood",
    "云杉木": "spruce_wood",
    "白桦木": "birch_wood",
    "丛林木": "jungle_wood",
    "金合欢木": "acacia_wood",
    "深色橡木": "dark_oak_wood",
    "红树木": "mangrove_wood",
    "樱树木": "cherry_wood",
    "橡木树苗": "oak_sapling",
    "云杉树苗": "spruce_sapling",
    "白桦树苗": "birch_sapling",
    "丛林树苗": "jungle_sapling",
    "金合欢树苗": "acacia_sapling",
    "深色橡木树苗": "dark_oak_sapling",
    "红树胎生苗": "mangrove_propagule",
    "樱花树苗": "cherry_sapling",

    # ── 工具 ──
    "木镐": "wooden_pickaxe",
    "石镐": "stone_pickaxe",
    "铁镐": "iron_pickaxe",
    "金镐": "golden_pickaxe",
    "钻石镐": "diamond_pickaxe",
    "下界合金镐": "netherite_pickaxe",
    "木斧": "wooden_axe",
    "石斧": "stone_axe",
    "铁斧": "iron_axe",
    "金斧": "golden_axe",
    "钻石斧": "diamond_axe",
    "下界合金斧": "netherite_axe",
    "木锹": "wooden_shovel",
    "石锹": "stone_shovel",
    "铁锹": "iron_shovel",
    "金锹": "golden_shovel",
    "钻石锹": "diamond_shovel",
    "下界合金锹": "netherite_shovel",
    "木锄": "wooden_hoe",
    "石锄": "stone_hoe",
    "铁锄": "iron_hoe",
    "金锄": "golden_hoe",
    "钻石锄": "diamond_hoe",
    "下界合金锄": "netherite_hoe",
    "钓鱼竿": "fishing_rod",
    "打火石": "flint_and_steel",
    "指南针": "compass",
    "时钟": "clock",
    "桶": "bucket",
    "水桶": "water_bucket",
    "岩浆桶": "lava_bucket",
    "牛奶桶": "milk_bucket",
    "剪刀": "shears",
    "弓": "bow",
    "箭": "arrow",
    "盾牌": "shield",
    "弩": "crossbow",
    "三叉戟": "trident",
    "烈焰棒": "blaze_rod",
    "烈焰粉": "blaze_powder",
    "末影珍珠": "ender_pearl",
    "末影之眼": "ender_eye",
    "骨粉": "bone_meal",
    "线": "string",
    "粘液球": "slime_ball",
    "刷怪蛋": "spawn_egg",

    # ── 武器 ──
    "木剑": "wooden_sword",
    "石剑": "stone_sword",
    "铁剑": "iron_sword",
    "金剑": "golden_sword",
    "钻石剑": "diamond_sword",
    "下界合金剑": "netherite_sword",

    # ── 盔甲 ──
    "皮革头盔": "leather_helmet",
    "皮革胸甲": "leather_chestplate",
    "皮革护腿": "leather_leggings",
    "皮革靴子": "leather_boots",
    "铁头盔": "iron_helmet",
    "铁胸甲": "iron_chestplate",
    "铁护腿": "iron_leggings",
    "铁靴子": "iron_boots",
    "金头盔": "golden_helmet",
    "金胸甲": "golden_chestplate",
    "金护腿": "golden_leggings",
    "金靴子": "golden_boots",
    "钻石头盔": "diamond_helmet",
    "钻石胸甲": "diamond_chestplate",
    "钻石护腿": "diamond_leggings",
    "钻石靴子": "diamond_boots",
    "下界合金头盔": "netherite_helmet",
    "下界合金胸甲": "netherite_chestplate",
    "下界合金护腿": "netherite_leggings",
    "下界合金靴子": "netherite_boots",
    "海龟壳": "turtle_helmet",

    # ── 食物 ──
    "苹果": "apple",
    "面包": "bread",
    "牛排": "cooked_beef",
    "熟猪排": "cooked_porkchop",
    "熟鸡肉": "cooked_chicken",
    "熟羊肉": "cooked_mutton",
    "熟兔肉": "cooked_rabbit",
    "生牛肉": "beef",
    "生猪排": "porkchop",
    "生鸡肉": "chicken",
    "生羊肉": "mutton",
    "生兔肉": "rabbit",
    "金苹果": "golden_apple",
    "附魔金苹果": "enchanted_golden_apple",
    "胡萝卜": "carrot",
    "金胡萝卜": "golden_carrot",
    "马铃薯": "potato",
    "烤马铃薯": "baked_potato",
    "毒马铃薯": "poisonous_potato",
    "甜菜根": "beetroot",
    "甜菜汤": "beetroot_soup",
    "蘑菇煲": "mushroom_stew",
    "兔肉煲": "rabbit_stew",
    "曲奇": "cookie",
    "蛋糕": "cake",
    "南瓜派": "pumpkin_pie",
    "西瓜片": "melon_slice",
    "紫颂果": "chorus_fruit",
    "干海带": "dried_kelp",
    "腐肉": "rotten_flesh",
    "蛛眼": "spider_eye",
    "发酵蛛眼": "fermented_spider_eye",
    "河豚": "pufferfish",
    "生鳕鱼": "cod",
    "生鲑鱼": "salmon",
    "熟鳕鱼": "cooked_cod",
    "熟鲑鱼": "cooked_salmon",
    "热带鱼": "tropical_fish",
    "糖": "sugar",
    "牛奶": "milk_bucket",
    "鸡蛋": "egg",

    # ── 方块（建筑/装饰）──
    "工作台": "crafting_table",
    "熔炉": "furnace",
    "高炉": "blast_furnace",
    "烟熏炉": "smoker",
    "酿造台": "brewing_stand",
    "附魔台": "enchanting_table",
    "铁砧": "anvil",
    "砂轮": "grindstone",
    "切石机": "stonecutter",
    "锻造台": "smithing_table",
    "织布机": "loom",
    "制图台": "cartography_table",
    "讲台": "lectern",
    "堆肥桶": "composter",
    "木桶": "barrel",
    "箱子": "chest",
    "末影箱": "ender_chest",
    "潜影盒": "shulker_box",
    "陷阱箱": "trapped_chest",
    "漏斗": "hopper",
    "发射器": "dispenser",
    "投掷器": "dropper",
    "活塞": "piston",
    "粘性活塞": "sticky_piston",
    "红石比较器": "comparator",
    "红石中继器": "repeater",
    "红石火把": "redstone_torch",
    "拉杆": "lever",
    "按钮": "button",
    "压力板": "pressure_plate",
    "铁门": "iron_door",
    "木门": "oak_door",
    "活板门": "trapdoor",
    "栅栏": "fence",
    "栅栏门": "fence_gate",
    "梯子": "ladder",
    "玻璃": "glass",
    "玻璃板": "glass_pane",
    "染色玻璃": "stained_glass",
    "染色玻璃板": "stained_glass_pane",
    "铁栏杆": "iron_bars",
    "砖块": "bricks",
    "石砖": "stone_bricks",
    "苔石砖": "mossy_stone_bricks",
    "书架": "bookshelf",
    "床": "bed",
    "红床": "red_bed",
    "蓝色床": "blue_bed",
    "绿色床": "green_bed",
    "黄色床": "yellow_bed",
    "白色床": "white_bed",
    "黑色床": "black_bed",
    "TNT": "tnt",
    "唱片机": "jukebox",

    # ── 植物 / 作物 ──
    "小麦": "wheat",
    "小麦种子": "wheat_seeds",
    "甘蔗": "sugar_cane",
    "竹子": "bamboo",
    "仙人掌": "cactus",
    "南瓜": "pumpkin",
    "西瓜": "melon",
    "可可豆": "cocoa_beans",
    "藤蔓": "vine",
    "睡莲": "lily_pad",
    "花": "flower",
    "玫瑰": "rose",
    "牡丹": "peony",
    "丁香": "lilac",
    "向日葵": "sunflower",
    "虞美人": "poppy",
    "矢车菊": "cornflower",
    "兰花": "blue_orchid",
    "绒球葱": "allium",
    "铃兰": "lily_of_the_valley",
    "凋零玫瑰": "wither_rose",

    # ── 怪物掉落 ──
    "骨头": "bone",
    "腐肉": "rotten_flesh",
    "火药": "gunpowder",
    "蜘蛛丝": "string",
    "蜘蛛眼": "spider_eye",
    "末影珍珠": "ender_pearl",
    "烈焰棒": "blaze_rod",
    "烈焰粉": "blaze_powder",
    "恶魂泪": "ghast_tear",
    "岩浆膏": "magma_cream",
    "幻翼膜": "phantom_membrane",
    "海龟鳞甲": "scute",
    "鳞甲": "armadillo_scute",
    "兔子皮": "rabbit_hide",
    "兔子脚": "rabbit_foot",
    "皮革": "leather",
    "羽毛": "feather",
    "墨囊": "ink_sac",
    "荧光墨囊": "glow_ink_sac",

    # ── 特殊 / 杂项 ──
    "经验瓶": "experience_bottle",
    "附魔书": "enchanted_book",
    "空瓶": "glass_bottle",
    "药水": "potion",
    "喷溅药水": "splash_potion",
    "滞留药水": "lingering_potion",
    "金粒": "gold_nugget",
    "铁粒": "iron_nugget",
    "蛋糕": "cake",
    "地图": "map",
    "空地图": "empty_map",
    "命名牌": "name_tag",
    "拴绳": "lead",
    "鞍": "saddle",
    "烟火之星": "firework_star",
    "烟花火箭": "firework_rocket",
    "不死图腾": "totem_of_undying",
    "望远镜": "spyglass",
    "刷子": "brush",
    "收纳袋": "bundle",

    # ── 下界 / 末地 ──
    "下界疣": "nether_wart",
    "下界砖": "nether_brick",
    "地狱砖": "nether_brick",
    "灵魂沙": "soul_sand",
    "灵魂土": "soul_soil",
    "荧石": "glowstone",
    "荧石粉": "glowstone_dust",
    "下界石英": "quartz",
    "紫珀块": "purpur_block",
    "紫颂花": "chorus_flower",
    "末地石": "end_stone",
    "龙息": "dragon_breath",
    "龙头": "dragon_head",
    "鞘翅": "elytra",

    # ── 实体 / 刷怪蛋 ──
    "僵尸刷怪蛋": "zombie_spawn_egg",
    "骷髅刷怪蛋": "skeleton_spawn_egg",
    "苦力怕刷怪蛋": "creeper_spawn_egg",
    "蜘蛛刷怪蛋": "spider_spawn_egg",
    "末影人刷怪蛋": "enderman_spawn_egg",
    "凋零骷髅刷怪蛋": "wither_skeleton_spawn_egg",
    "猪灵刷怪蛋": "piglin_spawn_egg",
    "烈焰人刷怪蛋": "blaze_spawn_egg",
    "蠹虫刷怪蛋": "silverfish_spawn_egg",
    "史莱姆刷怪蛋": "slime_spawn_egg",
    "村民刷怪蛋": "villager_spawn_egg",
    "铁傀儡刷怪蛋": "iron_golem_spawn_egg",
    "雪傀儡刷怪蛋": "snow_golem_spawn_egg",
}


# 反向映射：英文 snake_case → 中文名（用于给 LLM 返回中文结果）
EN_TO_CN: dict[str, str] = {v: k for k, v in CN_TO_EN.items()}


def cn_to_en(query: str) -> str | None:
    """中文名 → 英文 snake_case ID 的精确查找。"""
    return CN_TO_EN.get(query.strip())


def en_to_cn(name: str) -> str | None:
    """英文 snake_case ID → 中文名。"""
    return EN_TO_CN.get(name)


def fuzzy_cn_match(query: str) -> list[tuple[str, str]]:
    """子串匹配：从 CN_TO_EN 中找出所有包含 query 的中文名。

    返回 [(中文名, 英文ID), ...]，按中文名长度升序（越短越精确）。
    """
    query = query.strip()
    if not query:
        return []
    results = []
    for cn_name, en_id in CN_TO_EN.items():
        if query in cn_name:
            results.append((cn_name, en_id))
    results.sort(key=lambda x: len(x[0]))
    return results
